sudo: required
services:
  - docker

before_install:
  - docker build -t react-app-with-docker -f Dockerfile.dev .

script:
  - docker run  -e CI=true  react-app-with-docker npm run test -- --coverage